export const metadata = {
  title: "Terms of Service | E5 Elevator",
};

export default function TermsPage() {
  return (
    <article className="prose prose-slate max-w-none">
      <h1>Terms of Service</h1>
      <p className="text-sm text-slate-500">Last updated: February 2026</p>

      <h2>1. Service Description</h2>
      <p>
        E5 Elevator (&quot;the Service&quot;) generates AI-powered business case reports
        for organisations considering an upgrade from Microsoft 365 E3 to E5 licensing.
        Reports are generated using artificial intelligence and publicly available data.
      </p>

      <h2>2. Pricing and Payment</h2>
      <ul>
        <li>A free preview of the Executive Summary section is provided at no cost.</li>
        <li>The full report (all 9 sections, PDF, and PowerPoint) costs &pound;79 (one-time payment).</li>
        <li>Payments are processed securely via Stripe.</li>
        <li>All prices include VAT where applicable.</li>
      </ul>

      <h2>3. 30-Day Refresh Policy</h2>
      <p>
        After purchasing a report, you may regenerate it once within 30 days at no additional
        cost. This allows you to update the report if your requirements change. After 30 days,
        a new purchase is required.
      </p>

      <h2>4. Refund Policy</h2>
      <p>
        Due to the digital nature of the product, refunds are assessed on a case-by-case basis.
        If the Service fails to generate a report due to a technical error, you will receive a
        full refund. Contact us at support@e5elevator.com for refund requests.
      </p>

      <h2>5. Intellectual Property</h2>
      <p>
        Reports generated by the Service are for your use. You may share reports internally
        within your organisation and with your board of directors. You may not resell generated
        reports or use them to provide competing services.
      </p>

      <h2>6. Accuracy Disclaimer</h2>
      <p>
        Reports are generated by artificial intelligence and should be treated as a starting point
        for your business case, not as definitive professional advice. See our{" "}
        <a href="/legal/ai-disclaimer">AI Disclaimer</a> for full details.
      </p>

      <h2>7. Data Protection</h2>
      <p>
        We process your data in accordance with our{" "}
        <a href="/legal/privacy">Privacy Policy</a> and UK GDPR. Company data entered
        during report generation is used solely for report creation and is not shared with
        third parties.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        The Service is provided &quot;as is&quot;. We are not liable for business decisions
        made based on generated reports. Our maximum liability is limited to the amount
        paid for the report (&pound;79).
      </p>

      <h2>9. Changes to Terms</h2>
      <p>
        We may update these terms from time to time. Material changes will be communicated
        via the website. Continued use of the Service constitutes acceptance of updated terms.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These terms are governed by the laws of England and Wales. Any disputes shall be
        subject to the exclusive jurisdiction of the courts of England and Wales.
      </p>
    </article>
  );
}
