export const metadata = {
  title: "AI Disclaimer | E5 Elevator",
};

export default function AIDisclaimerPage() {
  return (
    <article className="prose prose-slate max-w-none">
      <h1>AI Disclaimer</h1>
      <p className="text-sm text-slate-500">Last updated: February 2026</p>

      <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 not-prose mb-6">
        <p className="text-sm text-amber-900 font-medium">
          Reports generated by E5 Elevator use artificial intelligence and should not be
          treated as professional advice. Always verify claims and consult with qualified
          professionals before making business decisions.
        </p>
      </div>

      <h2>1. How Reports Are Generated</h2>
      <p>
        E5 Elevator uses large language models (LLMs) to generate business case reports based on:
      </p>
      <ul>
        <li>Your questionnaire responses about your organisation</li>
        <li>Public data from Companies House</li>
        <li>Training data the AI model has been trained on (which includes publicly available Microsoft documentation, security research, and industry reports)</li>
        <li>Curated seed data including real breach case studies with verified sources</li>
      </ul>

      <h2>2. Citation Policy</h2>
      <p>
        Every factual claim in generated reports includes a source citation in the format
        <code>[Source: Name, URL, Date]</code>. However:
      </p>
      <ul>
        <li><strong>AI-generated citations may not always be accurate.</strong> The AI may cite sources that seem plausible but contain incorrect URLs or dates.</li>
        <li><strong>We verify seed data sources</strong> (breach case studies, compliance frameworks) but cannot guarantee every AI-generated citation.</li>
        <li><strong>Always verify citations</strong> before including them in board papers or official documents.</li>
      </ul>

      <h2>3. Limitations</h2>
      <h3>What AI reports are good for:</h3>
      <ul>
        <li>Starting point for your E5 business case</li>
        <li>Framework for structuring your argument</li>
        <li>Identifying relevant risk factors and compliance gaps</li>
        <li>Generating talking points for board discussions</li>
        <li>Saving time on research and formatting</li>
      </ul>
      <h3>What AI reports are NOT:</h3>
      <ul>
        <li>Professional consulting advice</li>
        <li>Guaranteed-accurate financial projections</li>
        <li>Legal or compliance guidance</li>
        <li>A substitute for a qualified security assessment</li>
        <li>Definitive ROI calculations (these require your actual cost data)</li>
      </ul>

      <h2>4. Financial Figures</h2>
      <p>
        Cost estimates, TCO comparisons, and ROI projections in reports are <strong>illustrative
        only</strong>. They are based on publicly available Microsoft pricing and industry benchmarks,
        not your actual licensing costs. Always verify figures against your Microsoft agreement
        and consult your finance team.
      </p>

      <h2>5. AI Model Information</h2>
      <p>
        Reports may be generated using one of the following AI models (selectable in settings):
      </p>
      <ul>
        <li>Google Gemini 2.0 Flash</li>
        <li>OpenAI GPT-4o Mini</li>
        <li>Anthropic Claude 3.5 Haiku</li>
      </ul>
      <p>
        Different models may produce different outputs for the same inputs. The AI model used
        is displayed in the report metadata.
      </p>

      <h2>6. User Responsibility</h2>
      <p>
        By using E5 Elevator, you acknowledge that:
      </p>
      <ul>
        <li>You will review and edit AI-generated content before presenting it</li>
        <li>You are responsible for verifying all claims and citations</li>
        <li>Business decisions based on report content are your responsibility</li>
        <li>The report editor is provided specifically so you can customise content to your needs</li>
      </ul>

      <h2>7. Feedback</h2>
      <p>
        If you find inaccurate information in a generated report, please let us know at
        support@e5elevator.com so we can improve our prompts and seed data.
      </p>
    </article>
  );
}
